# constants used across the project
EXPERIMENT_NAME = "HEART_DISEASE_CLF"
MODEL_NAME = EXPERIMENT_NAME + "_MODEL"
PREPROCESSOR_NAME = "PREPROCESSOR"
SCORE_NAME = "SCORE"
LABELS_NAME = "LABELS"

# Training pipeline
EXPERIMENT_NAME_TRAIN = f"{EXPERIMENT_NAME}_TRAIN"
PIPELINE_NAME_TRAIN = f"PIPELINE_{EXPERIMENT_NAME_TRAIN}"
PIPELINE_DESCRIPTION_TRAIN = "Training Pipeline for Heart Disease Classification"


# Inference pipeline
EXPERIMENT_NAME_INFER = f"{EXPERIMENT_NAME}_BATCH_INFER"
PIPELINE_NAME_INFER = f"PIPELINE_{EXPERIMENT_NAME_INFER}"
PIPELINE_DESCRIPTION_INFER = "Batch Inference Pipeline for Heart Disease Classification"
