#!/usr/bin/env bash
set -eux pipefail

sudo apt install jq

RESOURCE_GROUP_NAME="YOUR-AZUREML-RG"
AML_WORKSPACE_NAME="YOUR-AZUREML-NAME"
STORAGE_ACCOUNT_NAME="YOUR-STORAGE"
KV_SERVICE_PRINCIPAL_SECRET_NAME="YOUR-KEY-VAULT-NAME"
AML_VNET_NAME=""
AML_SUBNET_NAME=""
SUBSCRIPTION_ID=$(az account show | jq -cr .id)
TENANT_ID=$(az account show | jq -cr .homeTenantId)

DOTENV_FILE_PATH=".env"

echo $"ENV=dev" > ".env"
echo $"RESOURCE_GROUP_NAME=${RESOURCE_GROUP_NAME}" >> ${DOTENV_FILE_PATH}
echo $"SUBSCRIPTION_ID=${SUBSCRIPTION_ID}" >> ${DOTENV_FILE_PATH}
echo $"TENANT_ID=${TENANT_ID}" >> ${DOTENV_FILE_PATH}
echo $"AML_WORKSPACE_NAME=${AML_WORKSPACE_NAME}" >> ${DOTENV_FILE_PATH}
echo $"STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}" >> ${DOTENV_FILE_PATH}
echo $"KV_SERVICE_PRINCIPAL_SECRET_NAME=${KV_SERVICE_PRINCIPAL_SECRET_NAME}" >> ${DOTENV_FILE_PATH}
echo $"AML_VNET_NAME=${AML_VNET_NAME}" >> ${DOTENV_FILE_PATH}
echo $"AML_SUBNET_NAME=${AML_SUBNET_NAME}" >> ${DOTENV_FILE_PATH}
